// Generated by CoffeeScript 1.4.0
(function() {
  var _this = this;

  this.test('true should be truthy', function() {
    return _this.ok(true, 'true is not truthy!');
  });

  this.test('should be able to append to an array', function() {
    return _this.equal([1, 2], [1] + 2);
  });

}).call(this);
