// Generated by CoffeeScript 1.4.0
(function() {
  var jyql, q;

  jyql = require('../../lib/jyql');

  console.log("This is the list of live trains from Berkhamsted to London Euston...");

  q = "select * from html where url='http://ojp.nationalrail.co.uk/service/ldbboard/dep/EUS/BKM/To' and xpath='//div[@class=\"tbl-cont\"]/table/tbody/tr'";

  jyql(q, function(err, data) {
    console.log("err is: " + err);
    return console.log("data is: " + JSON.stringify(data));
  });

}).call(this);
