// Generated by CoffeeScript 1.4.0
(function() {
  var addScript, interpretNationalRailData, yql;

  interpretNationalRailData = function() {
    var data, rawData, _ref;
    data = [];
    rawData = nationalRailData;
    rawData = (rawData != null ? (_ref = rawData.query) != null ? _ref.results.tr : void 0 : void 0) || [];
    _.each(rawData, function(row) {
      var tempData, _ref1, _ref2, _ref3, _ref4;
      tempData = {
        arrivalTime: (new Tempus()).timeString(row.td[0].p + ":00"),
        source: (_ref1 = row.td[1]) != null ? _ref1.p : void 0,
        status: (_ref2 = row.td[2]) != null ? _ref2.p : void 0,
        platform: (_ref3 = row.td[3]) != null ? _ref3.p : void 0,
        detailsURL: row.td[4] != null ? "http://ojp.nationalrail.co.uk" + ((_ref4 = row.td[4]) != null ? _ref4.a.href : void 0) : void 0
      };
      return data.push(tempData);
    });
    return data;
  };

  addScript = function(script, callback) {
    var headID, newScript;
    headID = document.getElementsByTagName("head")[0];
    newScript = document.createElement('script');
    newScript.type = 'text/javascript';
    if ((script.match(/^http[\s\S]*/)) != null) {
      newScript.src = script;
      newScript.onload = function() {
        return callback(null);
      };
      headID.appendChild(newScript);
    } else {
      newScript.innerHTML = script;
      headID.appendChild(newScript);
      callback(null);
    }
    return null;
  };

  yql = function(query, namespace, callback) {
    var callbackFunctionSource, randomCallbackName, randomDataName,
      _this = this;
    if (namespace == null) {
      namespace = '';
    }
    if (namespace !== '') {
      namespace += '_';
    }
    randomDataName = namespace + Math.random().toString(36).substr(2, 7);
    randomCallbackName = namespace + Math.random().toString(36).substr(2, 7);
    callbackFunctionSource = "var " + randomDataName + " = { };\nvar " + randomCallbackName + " = function (data) { " + randomDataName + " = data; };";
    return addScript(callbackFunctionSource, function() {
      return addScript("http://query.yahooapis.com/v1/public/yql?format=json&callback=" + escape(randomCallbackName) + "&q=" + escape(query), function(err) {
        return callback(err, eval(randomDataName));
      });
    });
  };

  $(function() {
    var q;
    q = "select * from html where url='http://ojp.nationalrail.co.uk/service/ldbboard/dep/BKM/CLJ/To' and xpath='//div[@class=\"tbl-cont\"]/table/tbody/tr'";
    return yql(q, 'co_giacec_ButtaLaPasta', function(err, data) {
      return console.log(data);
    });
  });

}).call(this);
