// Generated by CoffeeScript 1.4.0
(function() {
  var addScript, jyql, root;

  addScript = function(script, callback) {
    var headID, newScript,
      _this = this;
    headID = document.getElementsByTagName("head")[0];
    newScript = document.createElement('script');
    newScript.type = 'text/javascript';
    if ((script.match(/^http[\s\S]*/)) != null) {
      newScript.src = script;
      newScript.onload = function() {
        return callback(null);
      };
      headID.appendChild(newScript);
    } else {
      newScript.innerHTML = script;
      headID.appendChild(newScript);
      callback(null);
    }
    return null;
  };

  jyql = function(query, callback) {
    var callbackFunctionSource, randomName,
      _this = this;
    if (!(callback != null) || typeof callback !== 'function') {
      return null;
    }
    if (!(query != null) || query === '') {
      return callback(new Error('No query was specified'), null);
    }
    randomName = 'jyql_' + Math.random().toString(36).substr(2, 7);
    callbackFunctionSource = "var " + randomName + "_data = { };\nvar " + randomName + "_function = function (data) { " + randomName + "_data = data; };";
    addScript(callbackFunctionSource, function() {
      return addScript("http://query.yahooapis.com/v1/public/yql?format=json&callback=" + escape(randomName + '_function') + "&q=" + escape(query), function(err) {
        if (!err && (eval(randomName + '_data').error != null)) {
          err = new Error(eval(randomName + '_data').error.description);
        }
        return callback(err, eval(randomName + '_data'));
      });
    });
    return null;
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.jyql = jyql;

}).call(this);
